// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO0OnTPegY4UU82J9oBdIUS4n4s36w2H0',
    appId: '1:99100154563:web:61af48082cd00950d22076',
    messagingSenderId: '99100154563',
    projectId: 'voyage-7c920',
    authDomain: 'voyage-7c920.firebaseapp.com',
    storageBucket: 'voyage-7c920.appspot.com',
    measurementId: 'G-RX3740XRK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb2KaSC7okHzJGWHjb4n5FL7SRGchpV6A',
    appId: '1:99100154563:android:bf4ca2d2ccf366b1d22076',
    messagingSenderId: '99100154563',
    projectId: 'voyage-7c920',
    storageBucket: 'voyage-7c920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzpfFLGCGl-4733AJ-HgNCpaE123D7S8',
    appId: '1:99100154563:ios:8615300453ced61fd22076',
    messagingSenderId: '99100154563',
    projectId: 'voyage-7c920',
    storageBucket: 'voyage-7c920.appspot.com',
    iosClientId: '99100154563-p0pt5seom9n197r99k2hrajqv3qnmt23.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}*/
